<?php
/**
 * OrderCreateModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Continuity CRM
 *
 * No descripton provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * OrderCreateModelTest Class Doc Comment
 *
 * @category    Class */
// * @description OrderCreateModel
/**
 * @package     Swagger\Client
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OrderCreateModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "OrderCreateModel"
     */
    public function testOrderCreateModel()
    {

    }

    /**
     * Test attribute "customer_id"
     */
    public function testPropertyCustomerId()
    {

    }

    /**
     * Test attribute "shipping_first_name"
     */
    public function testPropertyShippingFirstName()
    {

    }

    /**
     * Test attribute "shipping_last_name"
     */
    public function testPropertyShippingLastName()
    {

    }

    /**
     * Test attribute "shipping_address1"
     */
    public function testPropertyShippingAddress1()
    {

    }

    /**
     * Test attribute "shipping_address2"
     */
    public function testPropertyShippingAddress2()
    {

    }

    /**
     * Test attribute "shipping_city"
     */
    public function testPropertyShippingCity()
    {

    }

    /**
     * Test attribute "shipping_province"
     */
    public function testPropertyShippingProvince()
    {

    }

    /**
     * Test attribute "shipping_postal_code"
     */
    public function testPropertyShippingPostalCode()
    {

    }

    /**
     * Test attribute "shipping_country"
     */
    public function testPropertyShippingCountry()
    {

    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {

    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {

    }

    /**
     * Test attribute "billing_first_name"
     */
    public function testPropertyBillingFirstName()
    {

    }

    /**
     * Test attribute "billing_last_name"
     */
    public function testPropertyBillingLastName()
    {

    }

    /**
     * Test attribute "billing_address1"
     */
    public function testPropertyBillingAddress1()
    {

    }

    /**
     * Test attribute "billing_address2"
     */
    public function testPropertyBillingAddress2()
    {

    }

    /**
     * Test attribute "billing_city"
     */
    public function testPropertyBillingCity()
    {

    }

    /**
     * Test attribute "billing_province"
     */
    public function testPropertyBillingProvince()
    {

    }

    /**
     * Test attribute "billing_postal_code"
     */
    public function testPropertyBillingPostalCode()
    {

    }

    /**
     * Test attribute "billing_country"
     */
    public function testPropertyBillingCountry()
    {

    }

    /**
     * Test attribute "shipping_method_id"
     */
    public function testPropertyShippingMethodId()
    {

    }

    /**
     * Test attribute "affiliate_id"
     */
    public function testPropertyAffiliateId()
    {

    }

    /**
     * Test attribute "sub_id"
     */
    public function testPropertySubId()
    {

    }

    /**
     * Test attribute "ip_address"
     */
    public function testPropertyIpAddress()
    {

    }

    /**
     * Test attribute "order_products"
     */
    public function testPropertyOrderProducts()
    {

    }

    /**
     * Test attribute "payment_type"
     */
    public function testPropertyPaymentType()
    {

    }

    /**
     * Test attribute "credit_card_number"
     */
    public function testPropertyCreditCardNumber()
    {

    }

    /**
     * Test attribute "credit_card_expiration_month"
     */
    public function testPropertyCreditCardExpirationMonth()
    {

    }

    /**
     * Test attribute "credit_card_expiration_year"
     */
    public function testPropertyCreditCardExpirationYear()
    {

    }

    /**
     * Test attribute "credit_card_cvv"
     */
    public function testPropertyCreditCardCvv()
    {

    }

}
